### ISSUE TITLE
Equal Bounds in forall does not work in SMTLibTranslator

### ISSUE THREAD

**Issue by headri** [janhaag/PSE2011#100] opened 2012-03-06 00:54 UTC
The following program:
main(){}ensure forall x(1,1) x == 1;
has two problems:
1. Verifier says false but it should be true.
2. The following exception is thrown:  line 3:21 required (...)+ loop did not match anything at input ')'

**Comment by ratefuchs** [comment] 2012-03-06 11:59
1. Did you try the latest commit? I get true as answer.
2. I don't get this message. However, I get the message if range is left out.
   Therefore, I think you did not try the latest commit.

The output after leaving range out and validating is:

sat
(model 
  (define-fun x$1!0 () Int
    0)
)

(which is a valid result) so I think its a problem in the Z3 grammar.

**Comment by janhaag** [comment] 2012-03-06 22:20
As to 2: I, too, can only reproduce this with the range left out. Also, it isn't an exception, but an ANTLR error message, proving that the Z3 result grammar is indeed the culprit.

**Comment by janhaag** [comment] 2012-03-06 23:27
This issue seems to be fixed in HEAD

**Closed as completed by janhaag** 2012-03-06 23:27 UTC
Labels: Verifier/Z3
