### ISSUE TITLE
wp for finite recursions

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#17] opened 2012-02-15 14:22 UTC
Try to prove the following program. You will encounter the exception trace shown below:

int foo (int x) {
int y;
if (x <= 0) { y = 0; } else { y = foo(x-1); }
return y;
}
main () { int z = foo(42); }

Exception in thread "main" java.util.NoSuchElementException
        at java.util.Vector.lastElement(Vector.java:476)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:251)
        at ast.Conditional.accept(Conditional.java:64)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:631)
        at ast.StatementBlock.accept(StatementBlock.java:30)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:505)
        at ast.Function.accept(Function.java:34)
        at verifier.smtlib.SMTLibTranslator.visit(SMTLibTranslator.java:527)
        at ast.Program.accept(Program.java:40)
        at verifier.smtlib.SMTLibTranslator.getWPTree(SMTLibTranslator.java:73)
        at verifier.smtlib.z3.Z3.translate(Z3.java:32)
        at verifier.Verifier.call(Verifier.java:36)
        at verifier.VerifierInterface.verify(VerifierInterface.java:28)
        at misc.ExecutionHandler.verify(ExecutionHandler.java:135)
        at gui.controller.MainController.widgetSelected(MainController.java:268)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at gui.MainFrame.openWindow(MainFrame.java:256)
        at gui.controller.MainController.initMainFrame(MainController.java:97)
        at gui.controller.MainController.<init>(MainController.java:85)
        at misc.MainClass.main(MainClass.java:18)

**Comment by ratefuchs** [comment] 2012-03-03 20:25
Not reproducible in current version - seems to be fixed with cceec20.

**Closed as completed by ratefuchs** 2012-03-03 20:25 UTC
Labels: Verifier/SMTLib
